export type UserRole = 'admin' | 'employee';

export interface UserAccount {
  id: string; // Document ID (usually Google Auth UID, or autogenerated for manually added employees)
  email: string;
  displayName: string; // Firstname - Lastname
  nickname: string;
  role: UserRole;
  createdAt?: any;
  lastLoginAt?: string;
  photoURL?: string;
  googleAccessToken?: string;
}

export type RoomId = 'room1' | 'room2' | 'room3' | '';

export interface MeetingRoom {
  id: RoomId;
  name: string;
  displayName: string;
  capacity: number;
  amenities: string[];
  color: string; // Tailwind class color
  bgLight: string;
  borderClass: string;
}

export type BookingStatus = 'pending' | 'approved' | 'rejected';
export type MeetingPlatform = 'meet' | 'teams' | 'zoom' | 'external' | 'none';
export type EntryType = 'meeting' | 'announcement';
export type AnnouncementCategory = 'out_of_office' | 'travel' | 'general' | 'leave' | 'urgent';

export interface Booking {
  id: string;
  title: string;
  description: string;
  roomId: RoomId;
  roomName: string;
  startTime: string; // ISO String (e.g. 2026-07-02T10:00:00)
  endTime: string; // ISO String
  creatorEmail: string;
  creatorName: string;
  status: BookingStatus;
  attendees: Array<{
    email: string;
    displayName: string;
    nickname?: string;
  }>;
  meetingType: MeetingPlatform;
  meetingLink: string;
  googleEventId?: string;
  createdAt: any;
  approvedBy?: string;
  rejectedReason?: string;
  isConfidential?: boolean;
  approvalKey?: string; // Secret key for direct one-click approve/reject via email
  reminder15mSent?: boolean; // Flag indicating 15m reminder email has been dispatched
  reminder15mSentAt?: string;

  // Announcement & Notice fields
  entryType?: EntryType; // 'meeting' (default) or 'announcement'
  isAllDay?: boolean;    // true for all-day notices like "ซ้อไปใต้"
  announcementCategory?: AnnouncementCategory;
  color?: string;        // 'purple', 'indigo', 'emerald', 'amber', 'rose', 'sky'
}

export interface ActivityLog {
  id: string;
  bookingId?: string;
  action: string; // e.g., 'created', 'approved', 'rejected', 'cancelled'
  details: string;
  userEmail: string;
  userName: string;
  timestamp: any;
}
